logo:
header: "Pretty Rough Shape"
title: Pretty Rough Shape
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
domain: "evelios.github.io" # the base hostname for your site, e.g. example.com
url: "https://prettyroughshape.com" # the base hostname & protocol for your site, e.g. http://example.com


# Author settings
author-pic: AboutPortrait.png # your photo
author-name: Garry Waters # your name
about-author: > # about author
  Just a dude in pretty rough shape
email: PrettyRoughShape@gmail.com # your email
phone: (555)-555-5555 # your phone number
website: https://prettyroughshape.com # you website


# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link


# Paginate
paginate: 24
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll
  - jekyll-paginate
  - jekyll-sitemap
  - faraday-retry

include: [_pages]

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - README.md